SELECT
    county_code,
    derived_ethnicity,
    derived_race,
    derived_sex,
    action_taken,
    purchaser_type,
    loan_type,
    TRY_CAST(loan_amount AS DOUBLE) AS loan_amount,
    TRY_CAST(interest_rate AS DOUBLE) AS interest_rate,
    TRY_CAST(loan_to_value_ratio AS DOUBLE) AS loan_to_value_ratio,
    TRY_CAST(income AS DOUBLE) AS income,
    applicant_credit_score_type,
    "applicant_ethnicity-1" AS applicant_ethnicity1,
    "applicant_ethnicity-2" AS applicant_ethnicity2,
    applicant_ethnicity_observed,
    "applicant_race-1" AS applicant_race1,
    applicant_race_observed,
    applicant_sex,
    applicant_sex_observed,
    lei,
    applicant_age AS age,
    debt_to_income_ratio,
    loan_purpose,
    lien_status,
    "denial_reason-1" AS denial_reason1,
    "denial_reason-2" AS denial_reason2,
    "denial_reason-3" AS denial_reason3,
    "denial_reason-4" AS denial_reason4,
    rate_spread,
    TRY_CAST(property_value AS DOUBLE) AS property_value,
    occupancy_type,
    business_or_commercial_purpose,
    reverse_mortgage,
    "open-end_line_of_credit" AS open_end_line_of_credit,
    preapproval,
    total_units,
    year,
    state
FROM {{ source('raw', 'raw') }}
